version: "3.7"
networks:
  gitea:
    external: false
services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    labels:
        tsdproxy.enable: "true"
        tsdproxy.name: "gitea"
    env_file:
      - .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_USER_PASSWORD}
      - GITEA__repository__ROOT=/data/gitea/repositories
      - TZ=America/Chicago
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=America/Chicago
    networks:
      - gitea
    volumes:
      - ./gitea-postgres:/var/lib/postgresql/data