version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    labels:
        tsdproxy.enable: "true"
        tsdproxy.name: "gitea"
    env_file:
      - .env
    environment:
      - USER_UID=${ENV_USER_UID}
      - USER_GID=${ENV_USER_GID}
      - TZ=${TIMEZONE}
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
