services:
  portainer-ce:
    env_file:
      - .env
    container_name: portainer
    labels:
        tsdproxy.enable: "true"
        tsdproxy.name: "portainer"
    ports:
      - ${PORT_1}:${PORT_1}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PATH_DATA}:/data
    image: portainer/portainer-ce:latest