services:
  portainer-ce:
    env_file:
      - .env
    ports:
      - ${PORT_1}:${PORT_1}
      - ${PORT_2}:${PORT_2}
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PATH_DATA}:/data
    image: portainer/portainer-ce:latest